@startuml

top to bottom direction

skinparam cloudBorderColor Gray
skinparam Padding 5

cloud {
component [DataBaseDs] <<Device Server>> as DBDS #LightSteelBlue
component [TangoAccessControl] <<Device Server>> as TAC #LightSteelBlue
}

cloud {
component [Server 1] <<Device Server>> as DS1 #LightSteelBlue
component [Server 2] <<Device Server>> as DS2 #LightSteelBlue
}

component [Tango Schema] <<SQL Database>> as DB #DarkSeaGreen

component [Tango Client] <<Application>> as DP #Thistle

component [Motor] <<Hardware>> as HW1 #RosyBrown
component [Power Supply] <<Hardware>> as HW2 #RosyBrown

HW1 <.. DS1
HW2 <.. DS2

DS1 --> DBDS
DS2 --> DBDS

DBDS ..> DB
TAC  ..> DB

DP --> DBDS
DP --> TAC
DP --> DS1

@enduml
