@startuml

top to bottom direction

skinparam packageBorderColor Gray
skinparam Padding 5

package "TangoJS Panel" {

  component Dashboard as DB #Thistle
  component WidgetSelector as WS #Thistle
  component Menu as MENU #Thistle
}

package "TangoJS Web Components" {

  component "tangojs-tree-view" as TREE #DarkSeaGreen
  component "tangojs-some-widget" as WIDGETS #DarkSeaGreen
}

component "react-grid-layout" as RGL #RosyBrown
component "react-modal" as MODAL #DarkKhaki

DB --> RGL : uses

DB --> WIDGETS : contains

WS --> WIDGETS : creates

MENU --> MODAL : uses

MENU --> TREE : uses

MENU -> WS : triggers

@enduml
