@startuml

top to bottom direction

skinparam cloudBorderColor Gray
skinparam nodeBorderColor Gray
skinparam Padding 5

node "Web Browser" {
  [TangoJS\nWeb Components] <<Widget Collection>> as WC #DarkSeaGreen
  [TangoJS Core] <<API Library>> as Core #Thistle
  [HTTP Connector] <<TangoJS Connector>> as C1 #DarkKhaki
  [WebSocket Connector] <<TangoJS Connector>> as C2 #DarkKhaki
}

cloud {
  [HTTP Server] <<TangoJS Backend>> as B1 #RosyBrown
  interface HTTP #RosyBrown
  HTTP - B1

  [WebSocket Server] <<TangoJS Backend>> as B2 #RosyBrown
  interface WS #RosyBrown
  WS - B2

  [Tango Device Servers] as DevSrv #LightSteelBlue
  interface IIOP #LightSteelBlue
  IIOP - DevSrv
}

WC .d.> Core
Core .d.> C1
Core .d.> C2
C1 --> HTTP
C2 --> WS
B1 -do-> IIOP
B2 -do-> IIOP

note right of WC
  Web Components module contains a collection of
  reusable, self contained widgets,
  e.g. labels, edit boxes, buttons and more.

  The widgets can be easily included
  in client application's.
end note

note right of Core
  Core module offers APIs for programmatic access
  to Device Servers.
end note

note right of C1
  Connector modules are pluggable bridges between
  browser environment and server side proxies.
end note

@enduml
