@startuml

actor User as USER
box "TangoJS Panel" #White
  participant Menu as MENU #Thistle
  participant WidgetSelector as WS #Thistle
  participant Dashboard as DB #Thistle
  participant Store as STORE #Thistle
end box

activate MENU
activate DB
activate STORE

USER --> MENU : select device
MENU --> STORE : open widget selector
STORE --> WS: open
activate WS
USER --> WS : select widget
WS --> STORE : add widget
deactivate WS
STORE --> DB : update
deactivate MENU
deactivate WS
deactivate DB
deactivate STORE

@enduml
