@startuml

node "Web Browser" {
  [TangoJS\nWeb Components] as WC
  [TangoJS\nConnector 1] as C1
  [TangoJS\nConnector 2] as C2
  [TangoJS Core] as Core
}

node "Server (I)" {
  [Backend 1\n(HTTP)] as B1
}

node "Server (II)" {
  [Backend 2\n(WebSocket)] as B2
}

cloud "TANGO" {
  [Device Servers ...] as DevSrv
}

[DevSrv] <-u-> B1 : IIOP
[DevSrv] <-u-> B2 : IIOP
B1 <-u-> C1 : HTTP
B2 <-u-> C2 : WebSocket
Core ..> C1
Core ..> C2
Core <.. WC

@enduml
