@startuml

package "TangoJS Web Components" {
  [line-edit\nwidget] as WLineEdit
  [label\nwidget] as WLabel
  [trend\nwidget] as WTrend
  [form\nwidget] as WForm
  [Widget API]
  [...]
}

package "TangoJS Core" {
  [TangoJS API] as API
}

package "TangoJS Connector" {
  [Server] <-> HTTP
  HTTP <-> [Client]
}

cloud "TANGO" {
  IIOP <-> [Server]
  [Device Servers ...] <-> IIOP
}


[Client] <.u. [API]
[API] <.u. WLineEdit
[API] <.u. WLabel
[API] <.u. WTrend
[API] <.u. WForm

@enduml
