@startuml

cloud "CORBA" {

node "Server 1" {
  component "<<DeviceServer>>\nDataBaseds" as DBDS
'  component "<<DeviceServer>>\nTangoAccessControl" as TAC
}

node "Server 2" {
  component "<<DeviceServer>>\nDeviceServer 1" as DS1
  component "<<DeviceServer>>\nDeviceServer 2" as DS2
}

node "Client" {
  component "TANGO API" as DP
}

}

database "MySQL database" {
  component "TANGO Schema" as DB
}

component "Hardware 1" as HW1
component "Hardware 2" as HW2

HW1 <.u.> DS1
HW2 <.u.> DS2

DS1 <-u-> DBDS
DS2 <-u-> DBDS

DBDS <.d.> DB
' TAC  <.> DB

DP <-> DBDS
' DP <-> TAC
DP <-> DS1

@enduml
